""" module: settings
** Content **
Django settings for joy_it_game project.

Generated by 'django-admin startproject' using Django 2.1.10.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/

** Details **

@author: (c) Thomas Lüth 2019 / info@tlc-it-consulting.com
@created: 2019-10-02 
""" 

import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'crefico+i1+0fvn!imf641_y4r==_r4#oxkh&1b7leheoeo2t*'

# SECURITY WARNING: don't run with debug turned on in production!
# Hint: Has to be True for the game as otherwise some web-assets would not be delivered by the test-web-server... 
DEBUG = True

# Logging-level (overwritten by setting in local_settings.py):
LOG_LEVEL = 50  # @UnusedVariable

ALLOWED_HOSTS = ['*']

SITE_ID = 1 #needed for contrib.sites...



# Application definition

INSTALLED_APPS = [
    'tlu_joyit_game.apps.TluJoyitGameConfig', #the gamne itself
    'accounts.apps.AccountsConfig', # accounthandling / create account
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', #needed for cms / bootmenu
    'django.contrib.admindocs', #for documentation
    'cms', #needed for cms_tags and language_chooser
    'menus', #needed for cms
    'treebeard', #needed for menus
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware', #i18n support
]

ROOT_URLCONF = 'joy_it_game.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
       'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'tlu_joyit_game/templates/tlu_joyit_game'), os.path.join(BASE_DIR, 'tlu_joyit_game/templates/tlu_joyit_game/registration')],
         'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'joy_it_game.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'game_db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

SITE_ROOT = os.path.dirname(os.path.realpath(__name__)) #for below :)
LOCALE_PATHS = ( os.path.join(SITE_ROOT, 'locale'), )   #to locate the translation files

#supported languages
LANGUAGES = [
    ('de', _('German')),
    ('en', _('English')),
]

LANGUAGE_CODE = 'en' #startup language

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/assets/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "tlu_joyit_game/templates/assets"),
]

LOGIN_REDIRECT_URL = 'tlu_joyit_game:index'
LOGOUT_REDIRECT_URL = 'tlu_joyit_game:index'

# local settings carry email settings, set by the user
try:
    from joy_it_game.local_settings import *  # @UnusedWildImport
except ImportError:
    pass