# Generated by Django 2.1.10 on 2019-10-02 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_pid', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelnum', models.IntegerField(default=-1)),
                ('level_start', models.DateTimeField(default=None, null=True)),
                ('level_ended', models.DateTimeField(default=None, null=True)),
                ('points', models.IntegerField(default=0)),
                ('result', models.IntegerField(default=0)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tlu_joyit_game.Game')),
                ('prevLevel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_levels', to='tlu_joyit_game.Level')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='current_level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_levels', to='tlu_joyit_game.Level'),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
